name: continuous deployment
on:
  push:
    branches:
      - main #当master分支推送的时候,我们部署到生产服务器
      - test #当test分支推送的时候,我们部署到测试服务器

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    name: 部署到服务器 #deploy to production server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: 切换pnpm #switch to pnpm
        uses: dafnik/setup-node-pnpm@v3

      - name: 安装依赖 #install
        run: pnpm install

      - name: 构建 #build
        run: pnpm run build

      - name: 测试部署
        if: github.ref == 'refs/heads/test' #对test分支进行检测
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root'
          server: '${{ secrets.SERVER_IP }}' #测试服务器地址
          ssh_private_key: ${{ secrets.WEB_TOKEN }}
          local_path: './dist/*'
          remote_path: '/home/www' #服务器部署路径

      - name: 部署
        if: github.ref == 'refs/heads/main' #对main分支进行检测
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root'
          server: '${{ secrets.SERVER_IP }}' #正式服务器地址
          ssh_private_key: ${{ secrets.WEB_TOKEN }}
          local_path: './dist/*'
          remote_path: '/home/www' #服务器部署路径
