name: continuous deployment
on:
  push:
    branches:
      - main #当master分支推送的时候,我们部署到生产服务器
      - test #当test分支推送的时候,我们部署到测试服务器

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    name: 部署到服务器 #deploy to production server
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 切换pnpm #switch to pnpm
        uses: dafnik/setup-node-pnpm@v3

      - name: 安装依赖 #install
        run: pnpm install

      - name: 构建 #build
        run: pnpm run build

      - name: 测试部署
        if: github.ref == 'refs/heads/test' #对test分支进行检测
        uses: appleboy/scp-action@v0.1.7
        with:
          username: '${{ secrets.USER_NAME }}'
          host: '${{ secrets.SERVER_IP }}' #正式服务器地址
          key: ${{ secrets.WEB_TOKEN }}
          source: './dist/*'
          target: '/opt/1panel/apps/openresty/openresty/www/sites/${{ secrets.SERVER_IP }}/index' #服务器部署路径
          rm: true
          strip_components: 1 #去掉路径中的第一层目录

      - name: 正式部署
        if: github.ref == 'refs/heads/main' #对main分支进行检测
        uses: appleboy/scp-action@v0.1.7
        with:
          username: '${{ secrets.USER_NAME }}'
          host: '${{ secrets.SERVER_IP }}' #正式服务器地址
          key: ${{ secrets.WEB_TOKEN }}
          source: './dist/*'
          target: '/opt/1panel/apps/openresty/openresty/www/sites/${{ secrets.SERVER_IP }}/index' #服务器部署路径
          rm: true
          strip_components: 1
